### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by mubashir-rehman** [Arcticons-Team/Arcticons#150]
Gallery Go, Camera Go by Google. Proxy master. Fdroid Classic. 
[20210511_081546.zip](https://github.com/Donnnno/Arcticons/files/6460231/20210511_081546.zip)

**Comment by Donnnno** [comment]
Forgot to reply to this one, but I reused some already created icons for your requests. But I did create the F-Droid Classic icon:

![image](https://user-images.githubusercontent.com/31142286/118359996-0b042c00-b586-11eb-9927-98cbc08a9ebf.png)

**Comment by mubashir-rehman** [comment]
Can you please make a tutorial video on youtube or something of you creating the icon? It might help others contribute, too.

**Comment by Donnnno** [comment]
Hmm, I'll think about it. Have you seen the [contributing guide](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md)? It doesn't go in detail about programs & stuff, but it gives a pretty basic explanation about the do's & don't when creating an icon.

As for the programs I'd recommend using Inkscape for that, personally I'm using Adobe Illustrator because I learned everything with it and use it daily (for professional use too). There are plenty of getting started tutorials on YouTube for Inkscape that can explain to you the basics.
