### ISSUE TITLE
Apply Arcticons You on folder icon in Discreet Launcher

### ISSUE THREAD

**Issue by jcperil** [Arcticons-Team/Arcticons#1859]
Hi, Discreet Launcher allows folders. Is there a way to apply Arcticons You on that?

<p align="center"><img src="https://github.com/Donnnno/Arcticons/assets/89805719/cfd6be79-519a-49a3-bd38-b4927da11b74" width="150px"/></p>

**Comment by Donnnno** [comment]
If it has an intent (com.discretelauncher.something), we could make an icon for it.

Maybe the dev @falzonv know's if it's possible :)

**Comment by Donnnno** [comment]
@TotallyAvailable uhhhh, anything we can do with this block of code?

**Comment by kaanelloed** [comment]
The intent created for a folder is {discreetlauncher.folder/discreetlauncher.folder[folder name]}, so the launcher would have to be modified for this to work.

**Comment by kaanelloed** [comment]
The PR: https://github.com/falzonv/discreet-launcher/pull/322

We must hope that the dev will accept this

**Comment by Donnnno** [comment]
Wow, thanks @kaanelloed that's amazing!

**Comment by kaanelloed** [comment]
@TotallyAvailable In any case, right now Discreet Launcher doesn't search icon packs for the folder. So we need to make a PR anyway. I'm not sure how useful it would be to search folder name, but if we find use case, we can make another PR that searches for folder name first and then for number of apps it contains.

**Comment by Donnnno** [comment]
If Arcticons needs code, maybe it's better to apply it to the Candybar project as a whole. That way other icon packs can utilize it too :)

**Comment by falzonv** [comment]
Hello guys,

I am really sorry for the late answer!
Since my announce in https://github.com/falzonv/discreet-launcher/issues/314 (maintenance mode), I now also have computer-related health issues (repetitive strain injuries in both wrists) and had to reduce a lot my computer activities, and especially programming which includes Discreet Launcher.
Now it is going a bit better (thanks to a combination of reducing activities, having better ergonomics, using [Workrave](https://github.com/rcaelers/workrave) at work and at home, and seing a hand therapist) but I honestly still feel quite far from a full recovery...

Thank you @kaanelloed for the very good PR :-)
I wish to publish a release in February or March for some minor fixes and it will probably be included at the same time.

Some info about the current behavior:
- Folder icons are (re)generated only when the list of apps is updated and in the following way: there is a base icon on which the text for the number of apps in the folder is written, and the user-defined color for this folder is applied to both the base icon and the text (see the FolderIcon class in the first comment from @TotallyAvailable above).
- Adding/removing apps to/from a folder, or changing its user-defined color triggers an update of the list of apps.
- Since the base icon is the same for all folders, the user-defined color setting was added to better distinguish folders when their names are hidden.
- There is no limit to the number of apps in a folder, however the text would start to conflict with the base icon after 99 (I considered this case to be rare enough to not handle it).
- There is no restrictions on the user-defined color (same color picker than everywhere in the launcher), it can even have transparency.

Regarding the discussed options:
- I am not sure searching by folder name would work well in practice, the folder name is free text and even for common stuff (ex: "Games", "Tools") it would require many variants (ex: the previous examples would be "Jeux" and "Outils" for a French user, or some people may want to use variants like "Gaming", "Gaming!!!" or "Toolbox").
- Searching by number of apps is more reliable, but would require to create a lot of icons in the pack just to cover all numbers which is not very efficient...
- In either case, the feature for user-defined color per folder would be lost which might be an issue for some users.

Perhaps another strategy could be to try picking only the base icon in the pack?
That would require to adapt the PR to move its logic in the constructor of the FolderIcon class, and then let Discreet Launcher add the text and set the user-defined color.

And on the icon pack side:
- The intent would be "{discreetlauncher.folder/discreetlauncher.folder}" (skipping the folder name at the end).
- The icon would have to be designed in a way that allows the text (number of apps) to be added at the same position than the current base icon https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/res/drawable/icon_folder.xml (see the initial comment above for a preview, the |__| shape at the bottom of the icon is just large enough to fit a 2-digit number with the same gap size with the sides and bottom lines).
- The icon graphics should be monochromous (#FFFFFF) like in the current base icon.

What do you think about this?

Best regards.

(Note: I prefer not to say how long it took me to write all the above, which I think is necessary for the discussion, but don't expect too quick replies...)

**Comment by Donnnno** [comment]
Hi @falzonv thanks for all your hard work and detailed explanations of your implementation. 

Sounds fantastic to me, also sorry for the late reply 😅

I've added the intent to Arcticons so it should work when you push a new update.

**Comment by falzonv** [comment]
Hi @Donnnno,

Thank you for the kind words and the addition of the intent :-)

With also some delay on my side since the merge of the PR, the new release is now published and should be available soon in F-Droid and Google Play.

Best regards

**Comment by kaanelloed** [comment]
I think it's because version 9.0.0 have a double "{" in the component info : 
ComponentInfo{{discreetlauncher.folder/discreetlauncher.folder}

It's fixed in the main branch, so it should work in the next release.
