### ISSUE TITLE
daylight reproducible build failed

### ISSUE THREAD

**Issue by linsui** [Arcticons-Team/Arcticons#1952]
res/zIP.xml is missing in our build. Could you please take a look? Thanks!

**Comment by Donnnno** [comment]
zIP.xml, never seen that one before

**Comment by petlyh** [comment]
I took a look at it myself. It looks like the `daynight` and `you` APKs in your GitHub release includes `foodora_dk.xml`, which is not in the F-Droid builds since the `foodora_dk` icon doesn't exist in the repo after 2cd600b. `zIP.xml` is just the scrambled filename for that file, so this accounts for that difference. I also checked some of the files that differed and it looks like the only differences are the references that are auto-generated at build-time, which have probably just been offset by there being an extra file.

Diff of one of the files:

<img width="350" src="https://github.com/Arcticons-Team/Arcticons/assets/88139840/2c3c48e2-02a9-4f80-bef4-83eb722e0362">

**Comment by Donnnno** [comment]
Found it! @petlyh to the rescue :) Thanks a lot!

**Comment by Donnnno** [comment]
Just pushed a new release, hopefully it should be fixed now :)

**Comment by linsui** [comment]
[diff.html.zip](https://github.com/Arcticons-Team/Arcticons/files/14157472/diff.html.zip)
Looks like other flavor is not reproducible, either.

**Comment by Donnnno** [comment]
Hmm, very strange. @Kaiserdragon2 might this have something to do with recent changes to the preparerelease script & builder things?

**Comment by Kaiserdragon2** [comment]
yeah somehow some drawables aren't included in the drawable.xml for the fdroid build if i interpret the diff correctly. Normally every build should result in the same output.

**Comment by Kaiserdragon2** [comment]
i just build it (normal) and compared to the apk on github and i get the same output except the certs (thats expected)

**Comment by Donnnno** [comment]
> i just build it (normal) and compared to the apk on github and i get the same output except the certs (thats expected)

Is it possible it might be an F-Droid error?

**Comment by Kaiserdragon2** [comment]
Just build it on a linux machine and i get the same differnces (don't know why)

**Comment by Kaiserdragon2** [comment]
> > i just build it (normal) and compared to the apk on github and i get the same output except the certs (thats expected)
> 
> Is it possible it might be an F-Droid error?

More like my error some missing lines of code

**Comment by Donnnno** [comment]
Just in time! Thanks for the fix, otherwise we had to wait another week

**Comment by Donnnno** [comment]
Lets hope this fixes it!
https://github.com/Arcticons-Team/Arcticons/releases/tag/8.7.1-hotfix

**Comment by linsui** [comment]
It works, thanks!
