### ISSUE TITLE
link to keepassx

### ISSUE THREAD

**Issue by coastgnu** [Arcticons-Team/Arcticons#2146]
Would a link to a directory in Keepassx enable the use of Arctic on icons in keepassx?

If yes, could an installation of Arctic on icons create this link?

At least a HowTo wich shows how to add such a link by a user would be highly apprecciated!

**Comment by Donnnno** [comment]
You probably wanna make sure that this icon works with the app installed on your phone, right?

![image](https://github.com/Arcticons-Team/Arcticons/assets/31142286/47e771e9-aa3d-478a-aae7-28b0682023a8)

In order to achieve that, you have to gather the code with the icon request app, and add it to the appfilter in the /newicons folder.

https://github.com/Kaiserdragon2/IconRequest/

Make sure that the name inside `drawable"name"` is the same as the icon name.

**Comment by Donnnno** [comment]
https://docs.arcticons.com/contribute/github-guide
