### ISSUE TITLE
[IDEA] Webp icons?

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2227]
Given the fact that Arcticons is getting pretty chonky, it might be a good idea to look into webp icons instead of pngs.
I know that Candybar supports it, I don't know how good launcher support is tho.

Investigating this at a point sometime later

**Comment by Donnnno** [comment]
<img width="349" alt="Scherm­afbeelding 2024-08-02 om 13 16 20" src="https://github.com/user-attachments/assets/836c9eb1-25e8-4871-ac11-24a123fb7139">

<img width="361" alt="Scherm­afbeelding 2024-08-02 om 13 50 37" src="https://github.com/user-attachments/assets/3f54e454-a787-4b35-b29e-a4af3be98039">

**Comment by Kaiserdragon2** [comment]
If the launcher support is there i could rewrite the script to convert to webp

**Comment by kaanelloed** [comment]
I don't think it's a matter of launcher support. Unless, for some reason, there's a launcher that decompiles icon pack apk, they're all supposed to get the drawable from Resources.getDrawable(), so they'll get a BitmapDrawable whether it's a png or a webp. Since webp has been [fully supported](https://developer.android.com/studio/write/convert-webp) in Android since sdk 18, there should be no problem for any launcher.

**Comment by Donnnno** [comment]
Great to hear that!
